### ISSUE TITLE
Integrar AdminLTE a la plataforma

### ISSUE THREAD

**Issue by keimi** [DCC-CC4401/2017-2-Team-Cachupin-T3#21]
https://github.com/almasaeed2010/AdminLTE

**Comment by BastyZ** [comment]
Este es el trabajo en AdminLTE subido por el grupo Bizc8 a Material Alumnos

[Vistas_Bizc8.zip](https://github.com/DCC-CC4401/2017-2-Team-Cachupin-T3/files/1341818/Vistas_Bizc8.zip)
